// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LeftNav: typeof import('./src/components/leftNav.vue')['default']
    MyFooter: typeof import('./src/components/myFooter.vue')['default']
    MyHeader: typeof import('./src/components/myHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
